### ISSUE TITLE
linux下不能编译吗?

### ISSUE THREAD

**Issue by tsuibin** [wang-bin/PhotoKit#1]
缺少libezlog下的代码

**Comment by wang-bin** [comment]
git submodule init

git submodudle update

不过现在一个幻灯片效果库我闭源了，也许你网上找得到。这个项目没在维护了，写得很烂，等我有空了重构下再把该开源的开源。要看效果你可以在sourceforge上下载编译好的

**Comment by tsuibin** [comment]
我是Linux X86平台，那个上面编译好的没有linux x86的啊

**Comment by wang-bin** [comment]
哦。linux都自己编译的，当初都开源的。你用win跑下试试吧

在 2013年4月8日星期一，徐大树 写道：

**Comment by tsuibin** [comment]
没有win系统....

**Comment by wang-bin** [comment]
好吧。你有邮箱么？发你一份

在 2013年4月8日星期一，徐大树 写道：

**Comment by tsuibin** [comment]
63877278#qq.com 非常感谢

**Comment by wang-bin** [comment]
·¢ÁË

2013/4/8 Ðì´óÊ÷ notifications@github.com

**Comment by tsuibin** [comment]
git源里缺少 libexif/exif-data.h 这个文件
-I/home/tsuibin/code/PhotoKit/src/NextEffect/src/loki/include -I. -I/usr/X11R6/include -I../out/.moc/4.8.1 -o ../out/.obj/PhotoKit_linux_x64/ExifReader.o tools/ExifReader.cpp
tools/ExifReader.cpp:23:31: 致命错误： libexif/exif-data.h：没有那个文件或目录
编译中断。
make[1]: **\* [../out/.obj/PhotoKit_linux_x64/ExifReader.o] 错误 1
make[1]:正在离开目录 `/home/tsuibin/code/PhotoKit/src'
make: **\* [sub-src-PhotoKit-pro-make_default] 错误 2

**Comment by wang-bin** [comment]
git submodule 的代码拉了没？

在 2013年4月8日星期一，徐大树 写道：

**Comment by tsuibin** [comment]
拉了

------------------ 原始邮件 ------------------
发件人: "WangBin"notifications@github.com;
发送时间: 2013年4月8日(星期一) 中午1:23
收件人: "wang-bin/PhotoKit"PhotoKit@noreply.github.com; 
抄送: "徐大树"63877278@qq.com; 
主题: Re: [PhotoKit] linux下不能编译吗? (#1)

git submodule 的代码拉了没？ 

 在 2013年4月8日星期一，徐大树 写道：

**Comment by wang-bin** [comment]
那没道理呀。那个文件存在没？不行的话你装下linexif的dev包好了

在 2013年4月8日星期一，徐大树 写道：

**Comment by tsuibin** [comment]
文件不存在，安装libexif-dev之后编译通过了  :)

---------------- 原始邮件 ------------------
发件人: "WangBin"notifications@github.com;
发送时间: 2013年4月8日(星期一) 中午1:28
收件人: "wang-bin/PhotoKit"PhotoKit@noreply.github.com; 
抄送: "徐大树"63877278@qq.com; 
主题: Re: [PhotoKit] linux下不能编译吗? (#1)

那没道理呀。那个文件存在没？不行的话你装下linexif的dev包好了 

 在 2013年4月8日星期一，徐大树 写道：

**Comment by wang-bin** [comment]
那是没拉成功。。。

在 2013年4月8日星期一，徐大树 写道：
